### ISSUE TITLE
API - Not working with scheduleFilter=true/false

### ISSUE THREAD

**Issue by shansrii** [rundeck/docs#418] opened 2020-01-28 13:55 UTC
Below example, it is listing the job which is not scheduled
```
$ curl -s -H "X-Rundeck-Auth-Token: `cat ~/token`" -H "Accept: application/json" -k "https://rundeck-server:4440/api/34/project/Test/jobs?scheduledFilter=true"|jq .
  {
    "href": "https://rundeck-server:4440/api/34/job/857ce67b-5b7d-46fa-85f1-0adaawe8b6d0b",
    "id": "857ce67b-5b7d-46fa-85f1-0adaawe8b6d0b",
    "scheduleEnabled": false,
    "scheduled": false,
    "enabled": true,
    "permalink": "https:///rundeck-server:4440/project/PROD-Beamer/job/show/857ce67b-5b7d-46fa-85f1-0adaawe8b6d0b",
    "group": null,
    "description": "Analyse the files waiting for response",
    "project": "Test",
    "name": "analyze_WaitForResponse"
  },
```

**Comment by JeLuF** [comment] 2020-02-13 18:30
Duplicate of https://github.com/rundeck/rundeck/issues/5761

**Comment by shansrii** [comment] 2020-02-13 18:37
Closing the issue, since the fixed

**Closed as completed** 2020-02-13 18:37 UTC
