### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by ahumaidat** [rundeck/docs#186] opened 2018-12-26 08:29 UTC
Job State Conditional doesn't link to a the conditional state documentation page.

**Comment by gschueler** [comment] 2019-01-16 18:44
Which page did you find had the problem?

I filed a bug about missing content on the Builtin Workflow Steps page here: #198

**Comment by jessemarple** [comment] 2020-03-03 20:28
Duplicate of #198

**Closed by jessemarple** 2020-03-03 20:28 UTC
Labels: bug
